// Generated by scripts/train.ts — the learned evaluator's weights. Do not edit.
import type { NetWeights } from './net.js';
export const WEIGHTS: NetWeights = { sizes: [86, 1], w: [new Array(86).fill(0)], b: [[0]] };
