// THE EXPERIMENT FILE. This is the one file the research loop edits: architecture,
// optimiser, schedule, batch size, feature transforms, loss, regularisation. It is
// run under a fixed wall-clock budget and must print exactly one metric line:
//
//     METRIC val_mse=0.08531
//
// (lower is better). It also writes the trained weights to --out so a promising
// candidate can be taken into the strength eval (research/eval.ts).
//
//   npx tsx research/train.ts [--data data/research] [--budget 90] [--out data/research/candidate.ts]
//
// Rules of the road (see research/program.md): data and metric are frozen; the
// budget is the same for every run; only this file changes between experiments.
import { readFileSync, writeFileSync, statSync, openSync, readSync, closeSync } from 'node:fs';
import { Net } from '../src/server/net.js';
import { mkRng } from '../src/shared/rng.js';

function arg(name: string, def: string): string { const i = process.argv.indexOf(`--${name}`); return i >= 0 ? process.argv[i + 1]! : def; }
const dataDir = arg('data', 'data/research');
const budgetSec = Number(arg('budget', '90'));
const out = arg('out', `${dataDir}/candidate.ts`);

// ---- data (frozen) ----------------------------------------------------------
const meta = JSON.parse(readFileSync(`${dataDir}/meta.json`, 'utf8')) as { dim: number; train: number; val: number };
// Read in chunks: readFileSync refuses files over 2 GiB, and 26k games of 142-dim rows is 2.5 GB.
const load = (name: string) => {
  const path = `${dataDir}/${name}`;
  const size = statSync(path).size;
  const out = new Float32Array(size / 4);
  const bytes = new Uint8Array(out.buffer);
  const fd = openSync(path, 'r');
  const CHUNK = 1 << 28;
  for (let off = 0; off < size; off += CHUNK) readSync(fd, bytes, off, Math.min(CHUNK, size - off), off);
  closeSync(fd);
  return out;
};
const trainX = load('train.x.f32'), trainY = load('train.y.f32'), valX = load('val.x.f32'), valY = load('val.y.f32');
const dim = meta.dim;
const nTrain = trainY.length, nVal = valY.length;
const row = (X: Float32Array, i: number) => X.subarray(i * dim, (i + 1) * dim);

// ---- experiment knobs ---------------------------------------------------------
const HIDDEN = (process.env.HIDDEN ?? '64,32').split(',').map(Number);
const BATCH = 2048;
const LR0 = 1e-2;
const LR_DECAY_PER_EPOCH = 0.7;
const L2 = 1e-5;
const SEED = Number(arg('seed', '11'));

// ---- training under budget ------------------------------------------------------
const rng = mkRng(SEED);
const net = new Net([dim, ...HIDDEN, 1], rng);
const idx = new Uint32Array(nTrain); for (let i = 0; i < nTrain; i++) idx[i] = i;
const started = Date.now();
const valMse = () => { let s = 0; for (let i = 0; i < nVal; i++) { const d = net.predict(row(valX, i)) - valY[i]!; s += d * d; } return s / nVal; };
let epoch = 0, seen = 0;
let bestVal = Infinity, bestSnap = net.snapshot();
outer: for (;;) {
  for (let i = nTrain - 1; i > 0; i--) { const j = Math.floor(rng() * (i + 1)); const t = idx[i]!; idx[i] = idx[j]!; idx[j] = t; }
  const lr = LR0 * Math.pow(LR_DECAY_PER_EPOCH, epoch);
  for (let s = 0; s < nTrain; s += BATCH) {
    const ids = Array.from(idx.subarray(s, Math.min(nTrain, s + BATCH)));
    net.trainBatch(ids.map((i) => row(trainX, i)), ids.map((i) => trainY[i]!), lr, L2);
    seen += ids.length;
    if ((Date.now() - started) / 1000 > budgetSec) break outer;
  }
  epoch++;
  const v = valMse();
  if (v < bestVal) { bestVal = v; bestSnap = net.snapshot(); }
  console.error(`epoch ${epoch} done at ${((Date.now() - started) / 1000).toFixed(0)}s, val ${v.toFixed(5)}`);
}
// Export the best epoch-end checkpoint seen inside the budget, and report its error.
if (valMse() > bestVal) net.restore(bestSnap);
const mse = valMse();
console.error(`stopped after ${epoch} full epochs + partial, ${seen} samples seen, ${((Date.now() - started) / 1000).toFixed(0)}s`);
const j = net.toJSON();
writeFileSync(out, `// Generated by research/train.ts — candidate evaluator weights. Do not edit.\nimport type { NetWeights } from '../../src/server/net.js';\nexport const WEIGHTS_CANDIDATE: NetWeights = ${JSON.stringify(j)};\n`);
console.log(`METRIC val_mse=${mse.toFixed(5)}`);
