// Train the learned evaluator on self-play data and write its weights into
// src/server/weights.ts. Reports held-out error against two baselines: predicting
// the mean, and the hand-written evaluation (linearly rescaled), so it is obvious
// whether the net actually learned anything the heuristic doesn't know.
//
//   npx tsx scripts/train.ts data/selfplay-*.json [--epochs 12] [--hidden 64,32] [--out src/server/weights.ts]
import { readFileSync, writeFileSync } from 'node:fs';
import { Net } from '../src/server/net.js';
import { mkRng } from '../src/shared/rng.js';

function arg(name: string, def: string): string { const i = process.argv.indexOf(`--${name}`); return i >= 0 ? process.argv[i + 1]! : def; }
const files = process.argv.slice(2).filter((a, i, all) => !a.startsWith('--') && !(i > 0 && all[i - 1]!.startsWith('--')));
const epochs = Number(arg('epochs', '12'));
const hidden = arg('hidden', '64,32').split(',').map(Number);
const out = arg('out', 'src/server/weights.ts');

let dim = 0; const X: number[][] = [], Y: number[] = [], H: number[] = [];
for (const f of files) {
  const d = JSON.parse(readFileSync(f, 'utf8')) as { dim: number; x: number[][]; y: number[]; h: number[] };
  dim = d.dim; X.push(...d.x); Y.push(...d.y); H.push(...d.h);
}
if (!X.length) { console.error('no data'); process.exit(1); }
const rng = mkRng(7);
const idx = X.map((_, i) => i);
for (let i = idx.length - 1; i > 0; i--) { const j = Math.floor(rng() * (i + 1)); [idx[i], idx[j]] = [idx[j]!, idx[i]!]; }
const nVal = Math.floor(idx.length * 0.1);
const val = idx.slice(0, nVal), train = idx.slice(nVal);

const mean = (a: number[]) => a.reduce((s, v) => s + v, 0) / a.length;
const mse = (pred: (i: number) => number, ids: number[]) => mean(ids.map((i) => (pred(i) - Y[i]!) ** 2));
// Hand-eval baseline: best linear fit y ≈ a·h + b on the training split.
const hT = train.map((i) => H[i]!), yT = train.map((i) => Y[i]!);
const hm = mean(hT), ym = mean(yT);
let cov = 0, varh = 0; for (let k = 0; k < hT.length; k++) { cov += (hT[k]! - hm) * (yT[k]! - ym); varh += (hT[k]! - hm) ** 2; }
const a = cov / (varh || 1), b = ym - a * hm;
console.log(`${X.length} samples (dim ${dim}), ${train.length} train / ${val.length} val`);
console.log(`baseline mean:      val MSE ${mse(() => ym, val).toFixed(4)}`);
console.log(`baseline hand-eval: val MSE ${mse((i) => a * H[i]! + b, val).toFixed(4)}  (y ≈ ${a.toFixed(2)}·h + ${b.toFixed(2)})`);

const net = new Net([dim, ...hidden, 1], mkRng(11));
const batch = 64;
for (let ep = 0; ep < epochs; ep++) {
  for (let i = train.length - 1; i > 0; i--) { const j = Math.floor(rng() * (i + 1)); [train[i], train[j]] = [train[j]!, train[i]!]; }
  const lr = 2e-3 * Math.pow(0.7, ep);
  let loss = 0, nb = 0;
  for (let s = 0; s < train.length; s += batch) {
    const ids = train.slice(s, s + batch);
    loss += net.trainBatch(ids.map((i) => X[i]!), ids.map((i) => Y[i]!), lr); nb++;
  }
  console.log(`epoch ${ep + 1}/${epochs}: train MSE ${(loss / nb).toFixed(4)}  val MSE ${mse((i) => net.predict(X[i]!), val).toFixed(4)}  lr ${lr.toExponential(1)}`);
}
// Where does the net beat the hand eval? Late game vs early, by tiles left (feature 1).
for (const [lo, hi, label] of [[0.66, 1.01, 'early'], [0.33, 0.66, 'mid'], [0, 0.33, 'late']] as const) {
  const ids = val.filter((i) => X[i]![1]! >= lo && X[i]![1]! < hi);
  if (!ids.length) continue;
  console.log(`  ${label.padEnd(5)} (${ids.length}): net ${mse((i) => net.predict(X[i]!), ids).toFixed(4)}  hand ${mse((i) => a * H[i]! + b, ids).toFixed(4)}`);
}
const j = net.toJSON();
writeFileSync(out, `// Generated by scripts/train.ts — the learned evaluator's weights. Do not edit.\nimport type { NetWeights } from './net.js';\nexport const WEIGHTS: NetWeights = ${JSON.stringify(j)};\n`);
console.log(`wrote ${out} (${j.sizes.join('→')}, ${j.w.reduce((s, w) => s + w.length, 0)} weights)`);
